## torh.tensor 有四种常见的乘法
1、*
2、torch.mul
3、torch.mm
4、torch.matmul

In [3]:
import torch

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## 1. 点乘（*）
a与b 做 * 乘法，原则实如果 a 与 b 的 size 不同，则以某种方式将 a 或 b 进行复制，使得复制后的 a 与 b 的 size 相同，然后再将 a 和 b 做 element-wise 的乘法（对应位相乘）

### 1.1 * 标量

In [4]:
a = torch.ones(3,4)
print(a)

print(a * 2)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


### 1.2 * 一维向量

In [5]:
 # 2.1 tensor 与行向量做 *, 每列乘以行向量对应列的值（相当于把行向量的行复制，成为与 tensor 维度相同的 Tensor）
a = torch.ones(3,4)
print(a)

b  = torch.Tensor([1,2,3,4])
print(b)

print(a * b)

print('----------------------------------------------------------------')


# 2.2 tensor与列向量做*乘法的结果是每行乘以列向量对应行的值（相当于把列向量的列复制，成为与维度相同的Tensor）. 注意此时要求Tensor的行数与列向量的行数相等
c = torch.Tensor([1,2,3]).reshape(3,1)
print(c)

print(a*c)



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 2., 3., 4.])
tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])
----------------------------------------------------------------
tensor([[1.],
        [2.],
        [3.]])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


### 1.3 * 矩阵

In [6]:
# 如果两个二维矩阵 A 与 B 做点积 A*B，则要求 A 与 B 的维度完全相同，即 A 的行数 = B 的行数，A 的列数 = B 的列数
a = torch.tensor([[1, 2], [2, 3]])
print(a * a)

tensor([[1, 4],
        [4, 9]])


## torch.mul 与 * 的用法完全相同

In [7]:
a = torch.tensor([[1, 2], [2, 3]])
torch.mul(a,a)

tensor([[1, 4],
        [4, 9]])

## torch.mm
数学里的矩阵乘法，要求两个 Tensor 的维度满足矩阵乘法的要求

In [8]:
a = torch.ones(3,4)
b = torch.ones(4,2)
torch.mm(a, b)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

## torch.matmul
torch.mm 的 broadcast 版本

In [9]:
a = torch.ones(3,4)
b = torch.ones(5,4,2)
torch.matmul(a, b)


tensor([[[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.],
         [4., 4.]]])